### ISSUE TITLE
Thingworx 9 infinite Composer loading

### ISSUE THREAD

**Issue by sneaguptc** [ptc-iot-sharing/QueryBuilderWidgetTWX#13]
When importing the extension (QueryBuilder-min-1.2.2) in Thingworx 9.0.0-b9557, opening any mashup to Edit will cause the Composer to show the loading animation indefinitely. Users can load the mashup normally (to View).

![image](https://user-images.githubusercontent.com/45254830/88891705-467a7780-d24c-11ea-9da1-1187a4551610.png)

**Comment by BogdanMihaiciuc** [comment]
The temporary solution is to get the latest typescript support code from [https://github.com/ptc-iot-sharing/ThingworxWidgetSupportPackage](ThingworxWidgetSupportPackage) and use it to build (e.g. via `npm link`) the project.

After we fully test the updates to that library and publish it to npm, we will release updated versions for all impacted widgets.

**Comment by sneaguptc** [comment]
1. git clone https://github.com/ptc-iot-sharing/ThingworxWidgetSupportPackage.git
2. cd C:\Users\sneagu\Downloads\ThingworxWidgetSupportPackage
3. npm link
4. cd C:\Users\sneagu\Downloads\QueryBuilderWidgetTWX
5. npm link typescriptwebpacksupport
6. npm run build

What am I doing wrong?

![image](https://user-images.githubusercontent.com/45254830/88898407-59de1080-d255-11ea-82bb-b7b93f511600.png)

**Comment by BogdanMihaiciuc** [comment]
This is because the new support package splits up the IDE and runtime components. Thus in `ide.ts`, the import on the first line should be from:
https://github.com/ptc-iot-sharing/QueryBuilderWidgetTWX/blob/b4eb0feb634f9b4aeef910eb5a21d65f69d5bb78/src/QueryBuilder.ide.ts#L2
to:
```ts
import { ThingworxComposerWidget } from 'typescriptwebpacksupport/widgetidesupport';
```

Similarly, in `runtime.ts`, from:
https://github.com/ptc-iot-sharing/QueryBuilderWidgetTWX/blob/b4eb0feb634f9b4aeef910eb5a21d65f69d5bb78/src/QueryBuilder.runtime.ts#L1
to:
```ts
import { ThingworxRuntimeWidget, TWService, TWProperty } from 'typescriptwebpacksupport/widgetruntimesupport'
```

**Comment by stefan-lacatus** [comment]
I'll publish a new release this week to fix the issue.

**Comment by stefan-lacatus** [comment]
@sneaguptc: Can you test out https://github.com/ptc-iot-sharing/QueryBuilderWidgetTWX/releases/tag/1.2.3 in thingworx 9? The issue should be fixed.
